# Analiziranje planetov in lun 2. del

V tej datoteki analiziramo podatke iz spletne strani https://starwars.fandom.com/wiki/List_of_planets. V analizi nastopa 2210 primerkov (planetov in lun), za katere ločimo 5 kategorij (ime, regija, sektor,sistem, prebivalstvo):

In [7]:
import os
import pandas as pd

podatki_obdelani = 'CSV datoteke'
csv_2 = 'planeti-lune-2.csv'
pd.set_option("display.max_rows", 12) # Št. vrstic


path_2 = os.path.join(podatki_obdelani, csv_2)
planeti2 = pd.read_csv(path_2)
planeti2.index += 1

## 1. Osnovne informacije

### 1.1 Tabela podatkov

In [8]:
planeti2

,Ime,Regija,Sektor,Sistem,Prebivalstvo
1,5251977,Unknown,Unknown,Unknown,Unknown
2,Aaloth,Outer Rim Territories,Gaulus sector,Unknown,Twi'leks
3,Aargonar,Unknown,Unknown,Unknown,Humans
4,Ab Dalis,Outer Rim Territories,Unknown,Ab Dalis system,Unknown
5,Abafar,Outer Rim Territories,Sprizen sector,Abafar system,Various
...,...,...,...,...,...
2206,Zolan,Mid Rim Territories,Lambda sector,Unknown,Clawdites
2207,Zoph,Outer Rim Territories,Unknown,Unknown,Unknown
2208,Zygerria,Outer Rim Territories,Chorlian sector,Zygerria system,Zygerrians
2209,Zyzar,Unknown,Unknown,Unknown,Unknown
2210,Zyzek,Unknown Regions,Unknown,Zyzek system,Unknown

Opazimo lahko, da je mnogo podatkov predstavljenih kot 'Unknown' in ravno to dejstvo bomo uporabili v nadaljnji analizi.

## 2. Tabele

### 2.1 Pogostost začenic

Ponovno nas zanima katere začetnice prevladujejo. Ali lahko pričakjemo podobne rezultate?

In [9]:
zacetnice_ponovitve = {}
for i in "ABCDEFGHIJKLMNOPRSTUVWXYZ": # Zadošča angleška abeceda (imen planetov ne slovenimo)
    zacetnice_ponovitve[i] = 0
    for j in planeti2['Ime']:
        if i == j[0]:
            zacetnice_ponovitve[i] += 1
            
zacetnice = {'začetnice':list(zacetnice_ponovitve.keys()), 'ponovitve':list(zacetnice_ponovitve.values())}
zacetnice_pd = pd.DataFrame.from_dict(zacetnice)
zacetnice_pd = zacetnice_pd.set_index(['začetnice'])

In [10]:
# Izpis tabele
zacetnice_pd

           ponovitve
začetnice
A                164
B                110
C                142
D                 92
E                 58
...              ...
V                 80
W                 28
X                 12
Y                 32
Z                 24

[25 rows x 1 columns]

Ponovno z naskokom preladujejo planeti in lune z začetnico A.

### 2.2 Katera regija je najbolj zastopana?

In [15]:
def najpogostejsa_upodobitev(podatki):
    upodobitve = {}  # Slovar za shranjevanje števila upodobitev vsakega filma/serije

    for index, planet in podatki.iterrows():
        upodobitev = planet['Regija']

        if upodobitev in upodobitve:
            upodobitve[upodobitev] += 1
        else:
            upodobitve[upodobitev] = 1
    
    return upodobitve

upodobitve_planet2 = najpogostejsa_upodobitev(planeti2)

In [16]:
# Podatki za tabelo
podatki_tabela = {
    'Upodobitev': list(upodobitve_planet2.keys()),
    'Število planetov': list(upodobitve_planet2.values())
}

# Ustvarimo tabelo iz podatkov
tabela = pd.DataFrame(podatki_tabela)

# Uredimo tabelo po padajočem vrstnem redu števila planetov
tabela = tabela.sort_values(by='Število planetov', ascending=False)

tabela

                         Upodobitev  Število planetov
1             Outer Rim Territories               776
0                           Unknown               610
3               Mid Rim Territories               250
8             Inner Rim Territories               122
4                       Core Worlds               104
..                              ...               ...
13                Galactic Frontier                 6
15                  Western Reaches                 6
10  Outer Rim Territories,The Slice                 2
12                Republic frontier                 2
14                    Extragalactic                 2

[16 rows x 2 columns]